from . import db #Bring in db

class Airline(db.Model):
    __tablename__ = 'main_airline'
    index = db.Column(db.Integer, primary_key=True)
    Mkt_Ccode = db.Column(db.String)
    Mkt_Fl_No = db.Column(db.Integer)
    Dep_Airport	= db.Column(db.String)
    Arr_Airport = db.Column(db.String)
    Date = db.Column(db.Integer)
    Day_Week = db.Column(db.String)
    Sched_Dep_Time_OAG = db.Column(db.Integer)
    Gate_Dep_Time_Actual = db.Column(db.Integer)
    Sched_Arr_Time_OAG = db.Column(db.Integer)
    Gate_Arr_Time_Actual = db.Column(db.Integer)
    Sched_Elapsed_Time_CRS = db.Column(db.Integer)
    Actual_Gate_Gate_Time = db.Column(db.Integer)
    Dep_Delay_Time_Actual = db.Column(db.Integer)
    Arr_Delay_Time_Actual = db.Column(db.Integer)
    Elapsed_Time_Diff_Actual = db.Column(db.Integer)
    Wheels_Off_Time_Actual = db.Column(db.Integer)
    Wheels_On_Time_Actual = db.Column(db.Integer)
    Tail_Number = db.Column(db.String)
    Cancel_Code = db.Column(db.String)
    Mins_Late_Delay_Code_E_Carrier = db.Column(db.Integer)
    Mins_Late_Delay_Code_F_Weather = db.Column(db.Integer)
    Mins_Late_Delay_Code_G_NAS = db.Column(db.Integer)
    Mins_Late_Delay_Code_H_Security = db.Column(db.Integer)
    Mins_Late_Delay_Code_I_Late_Arr_Flight = db.Column(db.Integer)
    First_Gate_Dep_Time = db.Column(db.Integer)
    Total_Ground_Away_From_Gate = db.Column(db.Integer)
    Longest_Ground_Time_Away_From_Gate = db.Column(db.Integer)
    No_Landings_At_Div_Airport = db.Column(db.Integer)
    month = db.Column(db.String)
    Arr_Delay_Time_Actual_Flag = db.Column(db.Integer)
    Sched_Dep_Time_OAG_Block = db.Column(db.String)